### PR TITLE
Update the structure and add content

### PR DESCRIPTION
**Pull request by alfakini**

### CODE REVIEW

**Review by danielSbastos — CHANGES_REQUESTED** [review]
The comments left out are quite straightforward. Nevertheless, this is AWESOME!!! :tada: :balloon:. Really, but really, good job :slightly_smiling_face:

**Review by schweigert — APPROVED** [review]

**Review by edrd-f — CHANGES_REQUESTED** [review]

**Review by diogotrentini — COMMENTED** [review]
My review is work-in-progress.

**Review by pedroCervi — APPROVED** [review]

**Review by diogotrentini — CHANGES_REQUESTED** [review]
Awesome work 👏👏

**Review by diogotrentini — COMMENTED** [review]
Re-adding 2 comments that got outdated.

**Review by diogotrentini — APPROVED** [review]

**Review by danielSbastos — APPROVED** [review]

**Pull request merged**
